### ISSUE TITLE
M1 macbook

### ISSUE THREAD

**Issue by luc-vermeylen** [hcp4715/dockerHDDM#1]
Dear,

First of all, thank you very much for providing this docker image!

I was trying to install it on my macbook (M1 ARM chip) and i received the following error:

`docker run -it --rm --cpus=4 \
-v /home/hcp4715/hddm_docker:/home/jovyan/work \
-p 8888:8888 hcp4715/hddm:0.8 jupyter notebook
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: Mounts denied: 
The path /home/hcp4715/hddm_docker is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
ERRO[0000] error waiting for container: context canceled
`

So i'm assuming there is a problem with running it on the M1's ARM architecture? Is there a way around this? 

Best,
Luc

**Comment by luc-vermeylen** [comment]
Adding the platform after docker run removed the platform error message but still the mount is denied:

`docker run --platform linux/amd64 -it --rm --cpus=4 \
-v /home/hcp4715/hddm_docker:/home/jovyan/work \
-p 8888:8888 hcp4715/hddm:0.8 jupyter notebook
docker: Error response from daemon: Mounts denied: 
The path /home/hcp4715/hddm_docker is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/desktop/mac for more info.
ERRO[0000] error waiting for container: context canceled
`

**Comment by luc-vermeylen** [comment]
After adding /home to the shared paths in Docker Desktop (Docker -> prefrences -> resources -> file sharing) it worked!

**Comment by hcp4715** [comment]
Hi, @luc-vermeylen,
Thanks for posting the issue. Really happy to know that you solve the problem and shared your solution!
