### ISSUE TITLE
Problem with processing InferenceDataFromHDDM 

### ISSUE THREAD

**Issue by JunZheng-oct30** [hcp4715/dockerHDDM#13]
Thank you for developing dockerHDDM which is convenient for us to use. 

However, recently I had a problem running the InferenceDataFromHDDM code, it ran for a while and then got stuck and didn't continue. When I opened PowerShell, it presented ‘[W 12:28:48.150 NotebookApp] WebSocket ping timeout after 90018 ms.’ I'm not sure if this is the problem and I am confused about how to solve this problem, so I'm asking for your advice.

Here is my code to define the model and the screenshots of the code that has problems, thank you for your help!
[model1.txt](https://github.com/user-attachments/files/16324495/model1.txt)

![截图1](https://github.com/user-attachments/assets/0c6ab86d-47c0-4153-ba61-5baf099b4472)
![截图2](https://github.com/user-attachments/assets/554508e0-a2ca-440f-87c4-1da993982f37)
![截图3](https://github.com/user-attachments/assets/341dd3d1-fae4-4091-b637-d2aded972acb)

**Comment by JunZheng-oct30** [comment]
New update: I tried to use a smaller sample (from 2000 to 200), and it worked. So it is most likely a laptop performance issue, and I think I need to find a more powerful PC to try it out.

**Comment by hcp4715** [comment]
@JunZheng-oct30 yes, you probably need  ~30G or more for RAM.

**Comment by JunZheng-oct30** [comment]
Thank you @hcp4715 ! 
I just tried to run it on a 32G RAM PC and it worked!
