### ISSUE TITLE
An error when using the "InferenceDataFromHDDM" for HDDMRegressor model

### ISSUE THREAD

**Issue by Yikang1020** [hcp4715/dockerHDDM#3]
Recently when I use 'InferenceDataFromHDDM' for HDDMRegressor  model. I cannot convert the HDDM object to the netcdf.
My model, parameter, and erroroutput are as follows.
Thanks for developing the tool.

**Comment by Yikang1020** [comment]
![image](https://user-images.githubusercontent.com/86370181/217698594-1708b656-5124-4e31-8446-273e9d6aa4ab.png)
![image](https://user-images.githubusercontent.com/86370181/217698637-982586a0-37a8-4459-b232-f369b5d9f792.png)
![image](https://user-images.githubusercontent.com/86370181/217698670-b8c6c42c-a9c8-4335-bd5d-9a32ba1844e5.png)
![image](https://user-images.githubusercontent.com/86370181/217698776-a3b2cb0b-0f0a-4454-b3a8-c582a7218cd3.png)

**Comment by hcp4715** [comment]
Hi, @Yikang1020 ,

I tested your model using the example data and `p_map()` for parallel processing. I can not reproduce your error.  everything worked. 

I think the error might be caused by the data type of `ms1res`. You make check my code here: https://github.com/hcp4715/dockerHDDM_Guide/blob/master/temp/Notebook_for_Issues.ipynb

**Comment by Yikang1020** [comment]
Hi,
After comparing my simulate data and data_cavanagh and function "p_map(）" and Parallel()", I have solved the problem.

This problem is indenpented of function function "p_map(）" and Parallel()" and number of chains, it is caused by the index.

When HDDM object is converted to the Infdata, the index of the data must be unique, I use "reset_index“ to solve the problem.

The error is happened on "kabuki.hierarchcal.py", when it call the function "get_data_nodes()", it will operate based on index of data, when our index is not unique, the error happen.

For more details, please refer to https://github.com/Yikang1020/HDDM-parameter-recovery/blob/main/temp/issue1.ipynb
