### ISSUE TITLE
hddm098 doesn't reproduce Basic HDDM Tutorial

### ISSUE THREAD

**Issue by zenkavi** [hcp4715/dockerHDDM#4]
I'm guessing you might be aware of this and therefore haven't included an `example` folder in the `hddm:0.9.8` image yet but the simplest model from the tutorial (and the later ones with a `depends_on` specified too) do not currently run. Below is the error. Any tips on how to fix it?

```
m = hddm.HDDM(data)

No model attribute --> setting up standard HDDM
Set model to ddm
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-4bb414055345> in <module>
      2 
      3 # This will tailor an individual hierarchical DDM around your dataset.
----> 4 m = hddm.HDDM(data)
      5 # m = hddm.HDDM(data, depends_on={'v': 'stim'})
      6 # find a good starting point which helps with the convergence.

/opt/conda/lib/python3.8/site-packages/hddm/models/hddm_info.py in __init__(self, *args, **kwargs)
    156             self.model_config = kwargs.pop("model_config")
    157 
--> 158         super(HDDM, self).__init__(*args, **kwargs)
    159 
    160         # -------------------------------------------------------------------------------------

/opt/conda/lib/python3.8/site-packages/hddm/models/base.py in __init__(self, data, bias, include, wiener_params, p_outlier, **kwargs)
   1400         )
   1401 
-> 1402         super(HDDMBase, self).__init__(data, **kwargs)
   1403 
   1404     def __getstate__(self):

/opt/conda/lib/python3.8/site-packages/hddm/models/base.py in __init__(self, data, **kwargs)
     72 
     73         self.std_depends = kwargs.pop("std_depends", False)
---> 74         super(AccumulatorModel, self).__init__(data, **kwargs)
     75 
     76     def _create_an_average_model(self):

/opt/conda/lib/python3.8/site-packages/kabuki/hierarchical.py in __init__(self, data, is_group_model, depends_on, trace_subjs, plot_subjs, plot_var, group_only_nodes)
    352         self.db = None
    353 
--> 354         self._setup_model()
    355 
    356     def _setup_model(self):

/opt/conda/lib/python3.8/site-packages/kabuki/hierarchical.py in _setup_model(self)
    363 
    364         # constructs pymc nodes etc and connects them appropriately
--> 365         self.create_model()
    366 
    367     def __getstate__(self):

/opt/conda/lib/python3.8/site-packages/kabuki/hierarchical.py in create_model(self, max_retries)
    451 
    452         # Check whether all user specified column names (via depends_on) where used by the depends_on.
--> 453         assert set(flatten(list(self.depends.values()))).issubset(set(flatten(self.nodes_db.depends))), "One of the column names specified via depends_on was not picked up. Check whether you specified the correct parameter value."
    454 
    455     def create_nodes_db(self):

/opt/conda/lib/python3.8/site-packages/kabuki/utils.py in flatten(l)
     12 
     13 def flatten(l):
---> 14     return reduce(lambda x, y: list(x)+list(y), l)
     15 
     16 def pretty_tag(tag):

TypeError: reduce() of empty sequence with no initial value
```

**Comment by zenkavi** [comment]
Sorry, now saw the release notes. So changing the model to 

```
m = hddm.HDDM(data, include = ['v', 'a', 't', 'z'],
                        informative = True,
                        is_group_model = True)
```
 works. Is an update to the tutorials in the works? I could send a PR as I work through them if that helps.

**Comment by hcp4715** [comment]
Hi, @zenkavi,

thanks for your feedback!
It'll be really helpful if you send a PR!!

(sorry for the late response, its' a bit strange that I did not receive a reminder for new issues).

**Comment by zenkavi** [comment]
Hi there,

Just a quick note: I've been working on the tutorials and have most of it working.

I'm working on the PR for this repo on my branch here: https://github.com/zenkavi/dockerHDDM/tree/098_tutorials

but for it to work it will require another PR to the hddm repo to be merged and then I'd think the docker image would have to be rebuilt with the most recent version of the hddm.

I'll send the PR for this repo asap so you have the modified tutorials ready to go whenever hddm is updated and you can rebuild the image.

**Comment by hcp4715** [comment]
Hi, Zeynep, 

Thanks a lot! will added this in the example and update our "readme" file!

**Comment by zenkavi** [comment]
Should we close this now that HSSM exists?

**Comment by hcp4715** [comment]
Hi, @zenkavi ,

In my opinion, it's better to make this version work to enhance reproducibility in the field.

We can make this version of HDDM work by installing hddm directly from your forked hddm repo, which should have fixed the error, instead of from hddm-devs'. 

Let me know your thoughts.

**Comment by zenkavi** [comment]
Sorry I might not have been clear. I meant if we should close the issue not get rid of the image. I completely agree that the image should continue existing. 

Is there anything you'd want me to look at/test at this point?

**Comment by hcp4715** [comment]
Hi, @zenkavi 

No worries. I understand what you've said. What I meant: we can still fix the issue here in the docker image hddm098. However, we do not need to wait for the hddm-dev team to merge your change as you mentioned [here](https://github.com/hddm-devs/hddm/commit/b22d489490f53bb7aaeac0423f88dd75025ea088). Instead, I can update the images by installing hddm directly from your repo. 

That said, I will install hddm from this [commit](https://github.com/zenkavi/hddm/tree/b22d489490f53bb7aaeac0423f88dd75025ea088) in the Dockerfile, so the hddm inside the docker image hddm098 will work. And you can also create a pull request to `hcp4715/dockerHDDM` so that I can include the notebooks you created in here: https://github.com/zenkavi/dockerHDDM/tree/098_tutorials/hddm098/example. 

By doing so, the newer hddm098 docker image will fix the issue here, and can be used by others in the future. 

Does this work for you?

Best
Chuan-Peng

**Comment by zenkavi** [comment]
Sounds good. Hopefully there aren't any other issues on my lan-tutorial-fix branch. I don't have the time to test it more extensively but can look into it if anything arises in the future.

Thanks for taking care of this. Also for making this in the first place. It has been very helpful to me.

**Comment by hcp4715** [comment]
Great!
Glad to hear that this is helpful :).
