### ISSUE TITLE
predefined 'thin' argument in HDDM_0.8_tutorial image 

### ISSUE THREAD

**Issue by XiaoyuZeng** [hcp4715/dockerHDDM#8]
Hi all.
Many thanks for your time and effort in making dockerHDDM. 

When using the HDDM_0.8_tutorial image (https://github.com/hcp4715/dockerHDDM_Guide/blob/master/tutorial/dockerHDDM_tutorial.ipynb), I noticed that the thinning doesn't work. Specifically, I've set **thin=5** to improve the model convergence, but it turned out all of the samples were saved.

Then I noticed that the thin argument has been predefined in the model-specification function so that **thin=1** in all cases:
![image](https://github.com/hcp4715/dockerHDDM/assets/38243112/1247e732-e3df-406e-bac1-c2f3887fbbad)

Feel free to close this issue if this has been corrected in the latest version of dockerHDDM.

Best,
Xiaoyu

**Comment by panwanke** [comment]
This probelm has been fixed in new version of dockerHDDM. Now you could easily fit a model with `m.sample(500, burn = 100, thin = 4)`.
